#!/bin/sh

cat > /caddyfile << EOF
${Host} {
    proxy / ${Host}:${Port} {
        proxy_header X-Forwarded-Proto {scheme}
        proxy_header X-Forwarded-For {host}
        proxy_header Host {host}
    }
}
EOF

caddy --conf /caddyfile