#!/bin/sh

cat > /caddyfile << EOF
${hostname} {
    proxy / ${proxy_host}:${proxy_port} {
        proxy_header X-Forwarded-Proto {scheme}
        proxy_header X-Forwarded-For {host}
        proxy_header Host {host}
    }
}
EOF

cat /caddyfile

caddy --conf /caddyfile